# Generated by Django 2.2.10 on 2020-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('title', models.CharField(max_length=240)),
                ('fax', models.CharField(max_length=20)),
                ('direct', models.CharField(max_length=20, verbose_name='Direct Number')),
                ('office', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=240)),
                ('formSubmissionDate', models.DateField(auto_now_add=True, verbose_name='Form Submission Date')),
            ],
        ),
    ]
