# Generated by Django 2.2.10 on 2020-09-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='formSubmissionDate',
            field=models.DateTimeField(verbose_name='date submitted'),
        ),
    ]
