# Generated by Django 2.2.10 on 2020-09-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_forms', '0002_auto_20200927_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='formSubmissionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
