# Generated by Django 2.2.10 on 2020-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_forms', '0005_auto_20200929_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
