# Generated by Django 2.2.10 on 2020-10-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_forms', '0006_auto_20200929_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='BusinessCardForm',
        ),
    ]
