# Generated by Django 2.2.10 on 2020-10-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_forms', '0008_flyerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscardform',
            old_name='formSubmissionDate',
            new_name='submitted_on',
        ),
        migrations.RenameField(
            model_name='flyerform',
            old_name='formSubmissionDate',
            new_name='submitted_on',
        ),
    ]
